version: 2.1

orbs:
  docker: circleci/docker@1.2.1
  gcp-gke: circleci/gcp-gke@1.4.0
  gcp-gcr: circleci/gcp-gcr@0.12.0

jobs:
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    parameters:
      cluster:
        description: |
          Name of gke cluster
        type: string
      container:
        description: |
          Name of docker container with organization
        type: string
      deployment:
        description: |
          Name of k8 deployment
        type: string
      image:
        description: |
          Name of docker image with organization
        type: string
      tag:
        description: |
          Docker image tag
        type: string
      namespace:
        description: |
          K8 namespace
        type: string
    steps:
      - gcp-gke/install
      - run:
          name: Install gke-gcloud-auth-plugin
          command: |
            gcloud components update
            gcloud components install gke-gcloud-auth-plugin
            gke-gcloud-auth-plugin --version
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud container clusters get-credentials << parameters.cluster >>
      - gcp-gke/rollout-image:
          cluster: << parameters.cluster >>
          container: << parameters.container >>
          deployment: << parameters.deployment >>
          image: << parameters.image >>
          tag: << parameters.tag >>
          namespace: << parameters.namespace >>

  test:
    description: Run integration tests after deployment is finished
    docker:
      - image: circleci/golang:latest
    parameters:
      environment:
        description: |
          The environment to test
        type: string
    steps:
      - checkout
      - run: make test-<< parameters.environment >>

workflows:
  docker-build-push-deploy-dev:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: ntc-site-proxy
          tag: 0.0.0
          registry-url: gcr.io
          filters:
            branches:
              only:
                - dev
      - deploy:
          cluster: mf-dev
          container: ntc-site-proxy
          deployment: ntc-site-proxy
          image: gcr.io/pineappleworkshop/ntc-site-proxy
          tag: 0.0.0
          namespace: default
          filters:
            branches:
              only:
                - dev
          requires:
            - gcp-gcr/build-and-push-image


  docker-build-push-deploy-prod:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: ntc-site-proxy
          tag: 0.0.0
          registry-url: gcr.io
          filters:
            branches:
              only:
                - prod
      - deploy:
          cluster: mf-prod
          container: ntc-site-proxy
          deployment: ntc-site-proxy
          image: gcr.io/pineappleworkshop/ntc-site-proxy
          tag: 0.0.0
          namespace: default
          filters:
            branches:
              only:
                - prod
          requires:
            - gcp-gcr/build-and-push-image
